### PR TITLE
Enable concatination of any Filetype.

### PR DESCRIPTION
**Pull request by alwin-rewedigital**
This will fix: https://github.com/sapegin/grunt-bower-concat/issues/40

Also removed bwr/components from git index.

Hope it is ok, tried to keep the API stable, but if you wish, I can change it.
I don't know how you are handling the version bumping and changelog.

Greets!

EDIT: Sorry wrong Issue

### CODE REVIEW

**Comment by sapegin** [comment]
Can’t check the diff because it’s too long.

> Also removed bwr/components from git index.

It’s completely unrelated to this PR. Is there any reason to do that at all? If so please make a separate PR.

> I don't know how you are handling the version bumping and changelog.

Please [don’t change change log](https://github.com/sapegin/grunt-bower-concat/blob/master/Contributing.md#other-notes).

I think the API could be something like this:

```
dest: {
  js: ...,
  css: ...,
  ...
}
```

And it’d be easy to make it backward compatible for `dest` (I believe this is the only use case for most of the users).

**Comment by alwin-rewedigital** [comment]
>It’s completely unrelated to this PR. Is there any reason to do that at all? If so please make a separate >PR.

Because there is a line in the Contribution.md
> Don’t commit generated files: compiled from Stylus CSS, minified JavaScript, etc.

> Can’t check the diff because it’s too long.
That's why I commited it seperately. If you still like that I extract the commit, I can do it

**Comment by alwin-rewedigital** [comment]
So my tasks to get this PR done are:

1. extract cleanup commit for removing generated files from git index
2. remove changelog and version changes (sorry overseen that in the Contribution.md)
3. change the API the way you suggested (even though these changes are not Backwards compatible)

anything else?

**Comment by sapegin** [comment]
Yep!

:shipit:

**Comment by alwin-rewedigital** [comment]
I think it's the best if we close this PR and I open a new clean one (with squashed messages and the API you described)

**Comment by sapegin** [comment]
OK ;-)

**Pull request closed without merging**
